version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: test
  MYSQL_PASSWORD: 123456
  MYSQL_DATABASE: testdb
  REACT_APP_SERVER_PORT: 8080

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - back-tier
    restart: unless-stopped
  server:
    build: ./
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: localhost #mysql-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:8080
    networks:
      - front-tier
      - back-tier
    volumes:
      - ./:/app
    links:
      - mysql-db
    command: node server.js #npm start
networks:
  front-tier:
  back-tier: